### ISSUE TITLE
Calling peripheral(advertisement) never completes in a shared module targetting Android

### ISSUE THREAD

**Issue by HarrisonOfTheNorth** [JuulLabs/kable#342]
We have quite easily passed a Kable advertisement into the Kable-supplied ```CoroutineScope.peripheral``` extension function, with good results, in an ordinary Kotlin Multiplatform app (deploying to Android), with our successes being where we have coded such calls into the shared module of the Kotlin Multiplatform project itself.

However when we code the same calls into a module that we retrieve from mavenLocal(), it never completes.

Looking at the following:

```
    override suspend fun getPeripheral(kableAdvertisement: com.juul.kable.Advertisement): Peripheral? {
        var kableperipheral: com.juul.kable.Peripheral? = null
        coroutineScope {
            println("***BLE: BLESCANNER BEFORE")
            val myperipheral = peripheral(kableAdvertisement)
            println("***BLE: BLESCANNER AFTER 1")
            kableperipheral = myperipheral
            println("***BLE: BLESCANNER AFTER 2")
        }

        println("***BLE: BLESCANNER AFTER 3")

        return kableperipheral
    }
```

all of the println statements appear in the logcat console, doing so when we run this code in the shared module of the Kotlin Multiplatform app. (The override comes from the interface we declare as a good practice, nothing unusual here.)

However if we run this exact same code in a module that we have created separately and pulled in from mavenLocal() and also deploying to Android, the last println that actually prints in logcat is ***BLE: BLESCANNER BEFORE

We've tried many scope patterns and yet it continues to fail.

We've looked at the actual extension function within Kable itself that translates the expect call into it's Android actual counterpart, and everything looks normal, vis-a-vis:

*androidMain/.../Peripheral.kt starting at line 88:*

```
public actual fun CoroutineScope.peripheral(
    advertisement: Advertisement,
    builderAction: PeripheralBuilderAction,
): Peripheral = peripheral(advertisement.bluetoothDevice, builderAction)

public fun CoroutineScope.peripheral(
    bluetoothDevice: BluetoothDevice,
    builderAction: PeripheralBuilderAction = {},
): Peripheral {
    val builder = PeripheralBuilder()
    builder.builderAction()
    return AndroidPeripheral(
        coroutineContext,
        bluetoothDevice,
        builder.transport,
        builder.phy,
        builder.observationExceptionHandler,
        builder.onServicesDiscovered,
        builder.logging,
    )
}

public fun CoroutineScope.peripheral(
    identifier: Identifier,
    builderAction: PeripheralBuilderAction = {},
): Peripheral {
    val bluetoothDevice = BluetoothAdapter.getDefaultAdapter().getRemoteDevice(identifier)
    return peripheral(bluetoothDevice, builderAction)
}
```

Any ideas???

**Comment by twyatt** [comment]
Is there a particular reason to be wrapping with `coroutineScope`?
I believe it will allow the function to finish if the peripheral hasn't connected yet, but if the peripheral is connected when your `getPeripheral` is called, then it will suspend while the peripheral is connected. I imagine that that is not your desired behavior?

This is because, on connection, a child coroutine scope is spun up to handle forwarding characteristic changes. This child coroutine scope is a child of the scope used when creating the peripheral. Since `coroutineScope` suspend until all children have completed, this will cause the `coroutineScope` to suspend while the inner peripheral is connected.

The coroutine scope for the peripheral was intended as a safe guard from leaking connections (i.e. cancel the parent and you'll be assured that all peripherals of that scope have disconnected). In which case, you could just create another scope (e.g. `connectionScope`) that you use for the parent-child relationship.

To test if it is a coroutine scoping issue, you can try using `GlobalScope` (or creating a new `CoroutineScope`) for your peripheral, i.e.:

```kotlin
println("***BLE: BLESCANNER BEFORE")
val myperipheral = GlobalScope.peripheral(kableAdvertisement)
```

**Comment by Bluetooth-Compose** [comment]
Hi @twyatt ,

Thanks for your detailed response, and for spending the time!

The reason for ```coroutineScope``` is illustrated in the question, starting at line 88 of ```androidMain/.../Peripheral.kt ```, it is an extension function (and the only available method) that is provided by the Kable api that is used to convert a Kable Advertisement into a Kable Peripheral. 

The peripheral isn't connected when calling getPeripheral, this is the method that is called to create the peripheral in the first place, all that exists when the function is called is the Advertisment that is passed into it, and all of the Advertisement's properties eg. advertisement.name are available and are unblocking.

At the ouitset, the Peripheral hasn't yet been created, there is no way but to use a method that utilises peripheral(kableAdvertisement) so that the peripheral is created, and that is supplied by ```CoroutineScope.peripheral(..)```

```GlobalScope.peripheral(kableAdvertisement)``` blocks as well.

Remember, and as stated, this exact code already works if used as is inside a standard Kotlin Multiplatform solution, where it fails is if called in a module that was created as a separate library and imported via mavenLocal().

**Comment by HarrisonOfTheNorth** [comment]
Hi @twyatt ,

Thanks for your detailed response, and for spending the time!

The reason for coroutineScope is illustrated in the question, starting at line 88 of androidMain/.../Peripheral.kt , it is an extension function (and the only available method) that is provided by the Kable api that is used to convert a Kable Advertisement into a Kable Peripheral.

The peripheral isn't connected when calling getPeripheral, this is the method that is called to create the peripheral in the first place, all that exists when the function is called is the Advertisment that is passed into it, and all of the Advertisement's properties eg. advertisement.name are available and are unblocking.

At the ouitset, the Peripheral hasn't yet been created, there is no way but to use a method that utilises peripheral(kableAdvertisement) so that the peripheral is created, and that is supplied by CoroutineScope.peripheral(..)

GlobalScope.peripheral(kableAdvertisement) blocks as well.

Remember, and as stated, this exact code already works if used as is inside a standard Kotlin Multiplatform solution, where it fails is if called in a module that was created as a separate library and imported via mavenLocal().

**Comment by twyatt** [comment]
The code path that is executed for the `CoroutineScope.peripheral` extension function is fairly simple and it is surprising you're hitting this issue. The only thing that jumps out at me is that the [`AndroidPeripheral`](https://github.com/JuulLabs/kable/blob/ce759dd72a0af01628b7e371c5670a12222355cd/core/src/androidMain/kotlin/Peripheral.kt#L120) class loader [does spin up a thread](https://github.com/JuulLabs/kable/blob/ce759dd72a0af01628b7e371c5670a12222355cd/core/src/androidMain/kotlin/BluetoothDevice.kt#L47-L59) — perhaps it is causing you trouble?).

It has a conditional for the type of thread handling that is used, perhaps see if you get a different behavior pre Android 8.0 (O) and post Android 8.0 (O)?

**Comment by HarrisonOfTheNorth** [comment]
@twyatt Thanks, good idea, we had this working in it's own module in a very thorough POC a year ago, we're just going through both the kotlin and kable updates since to see if there has been a breaking change that affects the POC build, I'll update the issue with that investigation outcome, once done!

**Comment by twyatt** [comment]
Wow, crazy bizarre issue. Glad you got it resolved and thanks for sharing what fixed it!
