### ISSUE TITLE
Android Multiple BLE Connections | Latency on Observe Functionality

### ISSUE THREAD

**Issue by ercan** [JuulLabs/kable#503]
Hi,

I'm working on an Android app which connects 5 to 8 devices and these devices have a service which emits a simple ByteArray in each ~(4 to 10ms).

When I start observing this service for each devices, I start seeing huge package losses (80% or even heigher) for some devices (for some of them package loss is pretty acceptable like 0.48%). But when I connect only 1 or 2 devices, I see almost no package loss.

Is there any restriction with device count or do you if I miss a point?

**Comment by twyatt** [comment]
There isn't any known restrictions.

Kable feeds all characteristic changes (from the `BluetoothGattCallback`) into a `MutableSharedFlow` with an "unlimited" buffer:

https://github.com/JuulLabs/kable/blob/40973d5f50dd4346510f25dcd6296c62053c4cc6/core/src/commonMain/kotlin/Observers.kt#L46

If you're slow on the consuming side, you should just see memory usage grow rather than packets being dropped.

I can't really speak as to limitations there might be in the underlying Android BLE system though. Not sure how Android might handle a peripheral updating a characteristic faster than Android and retrieve the updated data.

---

What version of Android is this? Before Android 26 the threading model for BLE was wonky. 🤷 If you see different behavior pre vs. post Android 26 it might hint at a possible cause.
