### ISSUE TITLE
[Feedback `0.35.0-RC`]: Are GATT-related exceptions deprecated?

### ISSUE THREAD

**Issue by PavlosTze** [JuulLabs/kable#792]
With `0.34.0`, there was a need of catching more exceptions than the ones documented, for example we have the following cases:

## `Peripheral.connect`
```
catch (e: GattRequestRejectedException) {
    ...
} catch (e: GattStatusException) {
    ...
}
```

## `Peripheral.write`
```
} catch (e: GattWriteException) {
    ...
} catch (e: GattRequestRejectedException) {
    ...
} catch (e: GattStatusException) {
    ...
}
```

---

My question is, I read in the release version the following:

> In general, you should now only ever need to catch IOException when calling Kable functions, all other exceptions should be considered programming error (could've been prevented by pre-checking conditions). Pre-conditions that could change between a check and call are thrown as IOExceptions.

Does that means that we no longer have to catch the above exceptions?

**Comment by twyatt** [comment]
> Does that means that we no longer have to catch the above exceptions?

That is correct, you should only need to catch `IOException`. This is because the exception hierarchy was unified/commonized (if specific failure exceptions are thrown, they'll be sub-classes of either `IOException` or `IllegalStateException`). Whereas, you could let `IllegalStateException` crash the app (to capture it via your app crash reporting tool), as all `IllegalStateExceptions` should be preventable (e.g. thrown because BLE is unsupported, which could've been checked before making the call).

Regarding your examples specifically:

```kotlin
try {
    peripheral.connect()
} catch (e: GattRequestRejectedException) {
    ...
} catch (e: GattStatusException) {
    ...
}
```

With the above exceptions, your course of action does not differ based on which exception was thrown. With either exception, you can either abort the the connection process, or try again. There is no need to have unique logic based on the specific failure.  You just need to know if connect succeeded (no exception) or failed (`IOException`).

```kotlin
try {
    peripheral.write(..)
} catch (e: GattWriteException) {
    ...
} catch (e: GattRequestRejectedException) {
    ...
} catch (e: GattStatusException) {
    ...
}
```

Again, you're not going to need unique logic based on which of the above exceptions was thrown, instead, we can now just catch `IOException` to know that write did not succeed, and either inform the user, or try again.

The major benefit, is that `IOException` is `common` (whereas many of the exceptions in the examples above were platform specific), so we can now write I/O code _and_ corresponding error handling in `common` source set.

Definitely let me know though, if there are use-cases where unique logic was actually needed based on the specific failure case.

**Comment by PavlosTze** [comment]
> > Does that means that we no longer have to catch the above exceptions?
> 
> That is correct, you should only need to catch `IOException`. This is because the exception hierarchy was unified/commonized (if specific failure exceptions are thrown, they'll be sub-classes of either `IOException` or `IllegalStateException`). Whereas, you could let `IllegalStateException` crash the app (to capture it via your app crash reporting tool), as all `IllegalStateExceptions` should be preventable (e.g. thrown because BLE is unsupported, which could've been checked before making the call) so it is likely a programming error that should/can be fixed/prevented.
> 
> Regarding your examples specifically:
> 
> ```kotlin
> try {
>     peripheral.connect()
> } catch (e: GattRequestRejectedException) {
>     ...
> } catch (e: GattStatusException) {
>     ...
> }
> ```
> 
> With the above exceptions, your course of action does not differ based on which exception was thrown. With either exception, you can either abort the the connection process, or try again. There is no need to have unique logic based on the specific failure. You just need to know if connect succeeded (no exception) or failed (`IOException`).
> 
> ```kotlin
> try {
>     peripheral.write(..)
> } catch (e: GattWriteException) {
>     ...
> } catch (e: GattRequestRejectedException) {
>     ...
> } catch (e: GattStatusException) {
>     ...
> }
> ```
> 
> Again, you're not going to need unique logic based on which of the above exceptions was thrown, instead, we can now just catch `IOException` to know that write did not succeed, and either inform the user, or try again.
> 
> The major benefit, is that `IOException` is `common` (whereas many of the exceptions in the examples above were platform specific), so we can now write I/O code _and_ corresponding error handling in `common` source set.
> 
> Definitely let me know though, if there are use-cases where unique logic was actually needed based on a specific failure case(s).

I see, yes these are some valid points and currently as you said we don't take different actions based on "Gatt-related exceptions", so having to catch only `IOException` definitely helps in having cleaner code.

Thanks, I'm closing this issue as my question is answered and we don't need to "confuse" anyone who might think there is a real issue here.
